services:
  db:
    container_name: db-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventdb
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 8879:9090
    volumes:
      - ./docker-volume/prometheus/config/data:/prometheus
      - ./docker-volume/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 8878:3000
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: grafana
      GF_DATABASE_PASSWORD: ii2eejaesahGheiJ
      # DO NOT use these 4 env var in production
      # it will disable all logins and everyone can mess with your dashboards
      # without any form of authentications
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ORG_ROLE: Editor
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./docker-volume/grafana:/var/lib/grafana
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: my-redis-instance
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  pgdata: {}
  redis_data: {}
