global:
  # DO NOT use this value in production, it's only for demo purposes
  # I usually use around 15s or 30s value
  scrape_interval: 1s
scrape_configs:
  - job_name: "prom-demo"
    static_configs:
      - targets: ["host.docker.internal:8081"]
